version: '3.7'
services:
  spring-boot-school-management:
    container_name: spring-boot-school-management
    image: student-management:latest
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/school_management_base_refactor
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changeme
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

